# syntax=docker/dockerfile:1

FROM node:22-alpine
ENV NODE_ENV=production
WORKDIR /app

COPY ["package.json", "package-lock.json*", "./"]
RUN npm install --omit=dev

COPY ./dist/ .
ENTRYPOINT ["node", "./transaction-microservice/src/app.js"]
