services:
  mongo-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ~/volumes/examples/base/mongo-db:/data/db

  mongo-express-db:
    image: mongo-express
    restart: always
    ports:
      - 8091:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo-db:27017/

  user-microservice:
    image: user_microservice:1.0
    restart: always
    ports:
      - 3015:3015
    volumes:
      - ./rsa-keys:/app/rsa-keys:ro
    environment:
      DB_CONNECTION_STRING: mongodb://root:example@mongo-db:27017
      DB_NAME: db
      DB_USER_COLLECTION_NAME: users
      PORT: 3015
    
  transaction-microservice:
    image: transaction_microservice:1.0
    restart: always
    ports:
      - 3016:3016
    volumes:
      - ./rsa-keys/public.pem:/app/rsa-keys/public.pem:ro
    environment:
      DB_CONNECTION_STRING: mongodb://root:example@mongo-db:27017
      DB_NAME: db
      DB_TRANSACTION_COLLECTION_NAME: transactions
      JWT_PUBLIC_KEY: /app/rsa-keys/public.pem
      PORT: 3016

  nginx-front:
    image: nginx:1.21.6
    volumes:
      - ./front-host/build:/usr/share/nginx/html
    ports:
      - 89:80
    environment:
      - NGINX_PORT=80